apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: engame-dev

resources:
  - namespace.yaml
  - ../../base

images:
  - name: engame-api
    newName: 654654563866.dkr.ecr.ap-northeast-2.amazonaws.com/usb-dev-engame-api
    newTag: latest
  - name: engame-front
    newName: 654654563866.dkr.ecr.ap-northeast-2.amazonaws.com/usb-dev-engame-front
    newTag: latest
