apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: engame-dev
resources:
  - namespace.yaml
  - ../../base
images:
  - name: engame-api
    newName: 654654563866.dkr.ecr.ap-northeast-2.amazonaws.com/usb-dev-engame-api
    newTag: 1669be3d7187dbd302440d056e7f8ea2c729f19e
  - name: engame-front
    newName: 654654563866.dkr.ecr.ap-northeast-2.amazonaws.com/usb-dev-engame-front
    newTag: a9fc5b290b8dc17075c3c914069b84004b1f153d
